### ISSUE TITLE
BUG: Namespace is not enforced to be lowercase

### ISSUE THREAD

**Issue by marcelschork** [ui5-community/generator-ui5-ts-app#38]
When providing the namespace there is no check that the provided input contains only lowercase letters. Using uppercase letters leads to an invalid ```ui5.yaml``` and ```package.json``` file. 

![Image](https://github.com/user-attachments/assets/da6697cb-706c-46a8-98fb-e899b1a3871b)

![Image](https://github.com/user-attachments/assets/0fc37a57-61ba-4608-b74d-0e691edba884)

**Comment by akudev** [comment]
Fixed by https://github.com/ui5-community/generator-ui5-ts-app/commit/f54ea82b6d5394e5988d04e7ffb15db4eb2a07f6
