### ISSUE TITLE
Add testing skeleton to the template

### ISSUE THREAD

**Issue by jornfranke** [ui5-community/generator-ui5-ts-app#6]
Hi,

it would be great if a testing skeleton could be added to the TypeScript OpenUI5 template. The official Javascript examples on the website seems to include testing and I think it would be useful to include into the template as it always takes a bit of time to setup a skeleton for unit testing etc.

Thank you.

**Comment by vobu** [comment]
good point - and already in the works on all levels: unit-, component- and e2e-test.
still waiting for some "official" parts to drop in (e.g. TS defs/types for OPA5 being one of them).
will keep this open until a PR is possible - thanks for bringing this on the table!

**Comment by jornfranke** [comment]
Great! Thanks a lot for the quick feedback. I was wondering how this would be done and good to hear that there are plans. For now I will work with Jasmine, but for sure also try out the OPA5 one once it is there.

I am working now on an open source progressive web application (PWA) that should run on all devices. Typescript was given to use. It will be for now simple small notes application that uses an encrypted storage in the browser. Lets see how this evolves.

**Comment by petermuessig** [comment]
Testing is included now
